# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('start_working_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'system_users',
            },
        ),
    ]
