# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('courier_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Address')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_cabinet.User')),
            ],
            options={
                'db_table': 'courier_order',
            },
        ),
    ]
