# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('dateTimeDeliver', models.DateTimeField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
